In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
from sklearn.metrics import r2_score, mean_absolute_error, median_absolute_error, mean_absolute_percentage_error, mean_squared_error
from sklearn.preprocessing import TargetEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
import optuna

In [32]:
df = pd.read_csv("../data/processed/jakarta_properties_processed_tes.csv")

In [33]:
df.head()

,price_idr,district,bedrooms,bathrooms,garage,land_size_m2,building_size_m2,cluster,pool,mrt,tol,mall,city_Jakarta Barat,city_Jakarta Pusat,city_Jakarta Selatan,city_Jakarta Timur,city_Jakarta Utara,sub_district
0,21.947041,duren sawit,3.0,2.0,4.0,4.663439,4.691348,1,0,0,0,0,0,0,0,1,0,pondok kelapa
1,23.025851,kebayoran lama,6.0,5.0,2.0,5.379897,5.860786,0,0,0,0,0,0,0,1,0,0,pondok indah
2,23.858760,mampang prapatan,12.0,5.0,9.0,6.957497,6.685861,0,0,0,0,0,0,0,1,0,0,kemang
3,21.465203,kebayoran lama,4.0,5.0,1.0,4.158883,5.068904,0,0,0,0,0,0,0,1,0,0,kebayoran lama
4,21.598735,kebayoran lama,5.0,4.0,1.0,4.158883,5.075174,0,0,0,0,0,0,0,1,0,0,kebayoran lama

In [55]:
models_dict = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=500,
        max_depth=8,
        min_samples_split=5,
        min_samples_leaf=20,
        max_features="sqrt",
        n_jobs=-1,
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        objective='reg:absoluteerror',
        max_depth=10,
        learning_rate=0.05953139963770414,
        n_estimators=2747,
        subsample=0.8337433250519926,
        colsample_bytree=0.7543943678414979,
        gamma=0.032771478039126015,
        min_child_weight=6,
        reg_alpha=1.716855990003528,
        reg_lambda=6.819289477686187,
        random_state=42
    )
}

In [36]:
X = df.drop(columns=["price_idr"])
y = df["price_idr"]

te_district = TargetEncoder(
    smooth=1,
    cv=5,
    target_type='continuous'
    )

te_subdistrict = TargetEncoder(
    smooth=1,
    cv=5,
    target_type='continuous'
    )



X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train['district'] = te_district.fit_transform(X_train[['district']], y_train).flatten()
X_test['district'] = te_district.transform(X_test[['district']]).flatten()

X_train['sub_district'] = te_subdistrict.fit_transform(X_train[['sub_district']], y_train).flatten()
X_test['sub_district'] = te_subdistrict.transform(X_test[['sub_district']]).flatten()

In [59]:
import json


def train_single_model(model_name,model,X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    y_test_true = np.expm1(y_test)
    y_pred_true = np.expm1(y_pred)
    error_pct = (np.abs(y_pred_true - y_test_true) / y_test_true)

    result = {
        "Model" : model_name,
        "R2 Score":r2_score(y_test,y_pred),
        "MAE (mean)":mean_absolute_error(y_test_true,y_pred_true),
        "MDAE (median)": median_absolute_error(y_test_true,y_pred_true),
        "MAPE": mean_absolute_percentage_error(y_test_true,y_pred_true),
        "Q25": error_pct.quantile(0.25),
        "Q50": error_pct.quantile(0.50),
        "Q75": error_pct.quantile(0.75)
    }
    with open('../models/metrics_model.json', 'w') as f:
        json.dump(result, f, ensure_ascii=False, indent=4)

    # FEATURE IMPORTANCE
    if model_name in ["Decision Tree", "Random Forest", "XGBoost"]:
        feat_imp = pd.DataFrame({
            'feature': X_train.columns,
            'importance': model.feature_importances_
        }).sort_values(by='importance', ascending=False)

        print(feat_imp.head(10))

    return result

In [44]:
def run_models(X_train, y_train, X_test, y_test, models):
    
    all_results = []

    for model_name, model in models.items():
        print(f"\nTraining {model_name} ...")

        result = train_single_model(
            model_name = model_name,
            model = model,
            X_train = X_train,
            y_train = y_train,
            X_test = X_test,
            y_test = y_test
        )

        all_results.append(result)

        print(f"Metrix Evaluation : {model_name}")
        print(f"R2 Score : {result["R2 Score"]}")
        print(f"MAE (mean): {result["MAE (mean)"]}")
        print(f"MDAE (median) : {result["MDAE (median)"]}")
        print(f"MAPE : {result["MAPE"]}")
        
        all_results_df = pd.DataFrame(all_results)
    return all_results_df

In [39]:
def cross_validation(model, X_train, y_train, n_splits=5):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    y_binned = pd.qcut(y_train, q=10, labels=False)
    for model_name, model in models_dict.items():
        print(f"\nCross Validation {model_name} ...")
        scores = cross_val_score(
            model,
            X_train,
            y_train,
            cv=skf.split(X_train, y_binned),
            scoring='r2'
        )

        print(f"R2 per fold : {scores}")
        print(f"Rata-rata R2: {scores.mean():.4f}")
        print(f"Std deviasi  : {scores.std():.4f}")

In [40]:
cross_validation(model=models_dict, X_train=X_train, y_train=y_train, n_splits=5)

Cross Validation Linear Regression ...
R2 per fold : [0.87844689 0.87052376 0.86926306 0.86909712 0.87721855]
Rata-rata R2: 0.8729
Std deviasi  : 0.0041

Cross Validation Decision Tree ...
R2 per fold : [0.8786356  0.87079038 0.87059722 0.87254562 0.87566341]
Rata-rata R2: 0.8736
Std deviasi  : 0.0031

Cross Validation Random Forest ...
R2 per fold : [0.88812683 0.8806891  0.8808548  0.8813107  0.88669921]
Rata-rata R2: 0.8835
Std deviasi  : 0.0032

Cross Validation XGBoost ...
R2 per fold : [0.92283154 0.91815571 0.91427113 0.9152385  0.91969656]
Rata-rata R2: 0.9180
Std deviasi  : 0.0031

In [54]:
all_models_result = run_models(X_train = X_train, y_train = y_train, X_test = X_test, y_test = y_test, models = models_dict)
all_models_result

Training Linear Regression ...
Metrix Evaluation : Linear Regression
R2 Score : 0.8737819198849684
MAE (mean): 0.25195028225673755
MDAE (median) : 0.1978030447698913
MAPE : 0.011105622527010977

Training Decision Tree ...
               feature  importance
4         land_size_m2    0.664049
16        sub_district    0.165943
5     building_size_m2    0.113700
0             district    0.024204
2            bathrooms    0.007311
14  city_Jakarta Timur    0.005796
3               garage    0.005201
1             bedrooms    0.004804
15  city_Jakarta Utara    0.003069
12  city_Jakarta Pusat    0.001862
Metrix Evaluation : Decision Tree
R2 Score : 0.8866473290280551
MAE (mean): 0.2131366866670021
MDAE (median) : 0.13608996248795435
MAPE : 0.009416205146182804

Training Random Forest ...
                 feature  importance
4           land_size_m2    0.340003
5       building_size_m2    0.229892
16          sub_district    0.172927
0               district    0.123717
3                 garage    0.048748
2              bathrooms    0.029393
1               bedrooms    0.024390
14    city_Jakarta Timur    0.011734
12    city_Jakarta Pusat    0.007485
13  city_Jakarta Selatan    0.006115
Metrix Evaluation : Random Forest
R2 Score : 0.8840120451238366
MAE (mean): 0.24086196709336735
MDAE (median) : 0.18967381560399232
MAPE : 0.01061080147263277

Training XGBoost ...
                 feature  importance
4           land_size_m2    0.376015
14    city_Jakarta Timur    0.139233
5       building_size_m2    0.077518
16          sub_district    0.073878
0               district    0.069092
12    city_Jakarta Pusat    0.046528
15    city_Jakarta Utara    0.040314
2              bathrooms    0.037838
11    city_Jakarta Barat    0.037634
13  city_Jakarta Selatan    0.028582
Metrix Evaluation : XGBoost
R2 Score : 0.9225426443966076
MAE (mean): 0.18778790104831825
MDAE (median) : 0.1387881558583821
MAPE : 0.008285575387093933

,Model,R2 Score,MAE (mean),MDAE (median),MAPE,Q25,Q50,Q75
0,Linear Regression,0.873782,0.251950,0.197803,0.011106,0.004109,0.008791,0.015479
1,Decision Tree,0.886647,0.213137,0.136090,0.009416,0.002344,0.006037,0.013047
2,Random Forest,0.884012,0.240862,0.189674,0.010611,0.003840,0.008439,0.014960
3,XGBoost,0.922543,0.187788,0.138788,0.008286,0.002723,0.006156,0.011293

In [24]:
cv =KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Objective Function
def objective(trial):

    params = {
        "objective": "reg:absoluteerror",
        "max_depth": trial.suggest_int("max_depth", 3, 10),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            1e-3,
            0.3,
            log=True
        ),

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            4000
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.5,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.5,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            0,
            5
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            0,
            10
        ),

        "random_state": 42,
    }

    model = XGBRegressor(**params)

    score = cross_val_score(
        model,
        X,
        y,
        cv=cv,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1
    ).mean()

    return score

In [25]:
study = optuna.create_study(direction="maximize")

study.optimize(
    objective,
    n_trials=200
)

print("Best Score :", study.best_value)
print("Best Params:", study.best_params)

[I 2026-07-13 22:06:54,026] A new study created in memory with name: no-name-839f15ea-2fbd-4269-9525-178ba6f64558
[I 2026-07-13 22:07:40,805] Trial 0 finished with value: -0.3016535064210394 and parameters: {'max_depth': 3, 'learning_rate': 0.0791382596368106, 'n_estimators': 3751, 'subsample': 0.6146888036605882, 'colsample_bytree': 0.7500041380526439, 'gamma': 1.2637469019984953, 'min_child_weight': 1, 'reg_alpha': 4.966119416007219, 'reg_lambda': 0.0856875804572399}. Best is trial 0 with value: -0.3016535064210394.
[I 2026-07-13 22:07:59,342] Trial 1 finished with value: -0.31389655010340367 and parameters: {'max_depth': 3, 'learning_rate': 0.03055562712053071, 'n_estimators': 1502, 'subsample': 0.546456552247822, 'colsample_bytree': 0.5903367385070512, 'gamma': 3.36070785216789, 'min_child_weight': 5, 'reg_alpha': 4.409188570401527, 'reg_lambda': 3.714906793148376}. Best is trial 0 with value: -0.3016535064210394.
[I 2026-07-13 22:08:21,238] Trial 2 finished with value: -0.4311218532237325 and parameters: {'max_depth': 3, 'learning_rate': 0.001000289385495279, 'n_estimators': 1627, 'subsample': 0.5628051050786134, 'colsample_bytree': 0.7043017037434831, 'gamma': 0.4151630861382982, 'min_child_weight': 4, 'reg_alpha': 2.1916188282678184, 'reg_lambda': 4.356347955310057}. Best is trial 0 with value: -0.3016535064210394.
[I 2026-07-13 22:08:40,125] Trial 3 finished with value: -0.29283619255356524 and parameters: {'max_depth': 8, 'learning_rate': 0.010895147317195913, 'n_estimators': 868, 'subsample': 0.7758556810352684, 'colsample_bytree': 0.7688163839452307, 'gamma': 0.2756856098491639, 'min_child_weight': 5, 'reg_alpha': 0.13909109544032017, 'reg_lambda': 9.513288625671464}. Best is trial 3 with value: -0.29283619255356524.
[I 2026-07-13 22:08:42,927] Trial 4 finished with value: -0.3893156656101721 and parameters: {'max_depth': 4, 'learning_rate': 0.012964258235114223, 'n_estimators': 136, 'subsample': 0.9599139289956884, 'colsample_bytree': 0.9332635671312176, 'gamma': 1.4569584307282062, 'min_child_weight': 10, 'reg_alpha': 1.622710432224979, 'reg_lambda': 2.671659133735904}. Best is trial 3 with value: -0.29283619255356524.
[I 2026-07-13 22:09:44,333] Trial 5 finished with value: -0.30164682851965496 and parameters: {'max_depth': 5, 'learning_rate': 0.014921251834430934, 'n_estimators': 3677, 'subsample': 0.9341307440501185, 'colsample_bytree': 0.8190864891061218, 'gamma': 1.5849828999516835, 'min_child_weight': 9, 'reg_alpha': 1.0097227661000967, 'reg_lambda': 1.2878465390968208}. Best is trial 3 with value: -0.29283619255356524.
[I 2026-07-13 22:10:23,485] Trial 6 finished with value: -0.28765412793291967 and parameters: {'max_depth': 8, 'learning_rate': 0.05016094547560077, 'n_estimators': 2585, 'subsample': 0.751220159933564, 'colsample_bytree': 0.6843632326897686, 'gamma': 2.0499303481809417, 'min_child_weight': 7, 'reg_alpha': 0.20493104871444123, 'reg_lambda': 5.954607437154254}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:10:29,388] Trial 7 finished with value: -0.31542919163115696 and parameters: {'max_depth': 5, 'learning_rate': 0.012166405768802624, 'n_estimators': 470, 'subsample': 0.622749478772191, 'colsample_bytree': 0.7402500623124674, 'gamma': 0.6144355143884722, 'min_child_weight': 3, 'reg_alpha': 0.6116643998362026, 'reg_lambda': 0.8844974793260496}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:11:05,118] Trial 8 finished with value: -0.31279516654681105 and parameters: {'max_depth': 4, 'learning_rate': 0.008028952753325913, 'n_estimators': 2711, 'subsample': 0.8087585912340677, 'colsample_bytree': 0.5176133743874822, 'gamma': 3.090536234267825, 'min_child_weight': 8, 'reg_alpha': 3.9993596813153385, 'reg_lambda': 9.999998476465137}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:11:46,954] Trial 9 finished with value: -0.3093497845015606 and parameters: {'max_depth': 3, 'learning_rate': 0.10289359773405221, 'n_estimators': 3602, 'subsample': 0.8140609294326, 'colsample_bytree': 0.8175353926163412, 'gamma': 2.929069579134536, 'min_child_weight': 6, 'reg_alpha': 1.5928907027244987, 'reg_lambda': 8.917146356908292}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:12:15,232] Trial 10 finished with value: -0.3032755257263062 and parameters: {'max_depth': 10, 'learning_rate': 0.27984607909622566, 'n_estimators': 2569, 'subsample': 0.7120676512601941, 'colsample_bytree': 0.9661641154824279, 'gamma': 4.843761269844357, 'min_child_weight': 7, 'reg_alpha': 3.0785181020517265, 'reg_lambda': 6.640666676048236}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:12:31,743] Trial 11 finished with value: -0.3092799141700252 and parameters: {'max_depth': 8, 'learning_rate': 0.003287209691780055, 'n_estimators': 1092, 'subsample': 0.7681876943196003, 'colsample_bytree': 0.6241972219475967, 'gamma': 0.008664029022970032, 'min_child_weight': 6, 'reg_alpha': 0.016015336923453236, 'reg_lambda': 6.961656265301342}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:12:59,909] Trial 12 finished with value: -0.2882555506129227 and parameters: {'max_depth': 8, 'learning_rate': 0.05051211625296553, 'n_estimators': 2440, 'subsample': 0.7108731102534603, 'colsample_bytree': 0.6698705306358403, 'gamma': 2.317574442400063, 'min_child_weight': 3, 'reg_alpha': 0.04442159269638574, 'reg_lambda': 6.751284354550372}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:13:30,131] Trial 13 finished with value: -0.2878666848514377 and parameters: {'max_depth': 8, 'learning_rate': 0.04931974851404091, 'n_estimators': 2649, 'subsample': 0.6852647840420695, 'colsample_bytree': 0.6535401123407076, 'gamma': 2.2208991536156524, 'min_child_weight': 1, 'reg_alpha': 0.9620250422570016, 'reg_lambda': 6.274319156898481}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:14:07,751] Trial 14 finished with value: -0.2976105603458826 and parameters: {'max_depth': 7, 'learning_rate': 0.177257918707328, 'n_estimators': 3136, 'subsample': 0.8654501376983839, 'colsample_bytree': 0.5574791602450958, 'gamma': 2.3511296842603113, 'min_child_weight': 1, 'reg_alpha': 1.095071694659888, 'reg_lambda': 4.980367565234922}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:14:29,924] Trial 15 finished with value: -0.29821671648893744 and parameters: {'max_depth': 10, 'learning_rate': 0.029513297222280483, 'n_estimators': 2002, 'subsample': 0.6731402398063059, 'colsample_bytree': 0.6558304364143228, 'gamma': 4.0439368822836155, 'min_child_weight': 2, 'reg_alpha': 2.408120897038671, 'reg_lambda': 5.645612276623137}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:15:07,470] Trial 16 finished with value: -0.2886811128244251 and parameters: {'max_depth': 7, 'learning_rate': 0.03754230839305736, 'n_estimators': 3184, 'subsample': 0.6731212324677429, 'colsample_bytree': 0.8901956317832944, 'gamma': 2.0836204986998945, 'min_child_weight': 10, 'reg_alpha': 0.7969968248701402, 'reg_lambda': 8.018700678356026}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:15:34,148] Trial 17 finished with value: -0.29871559069288833 and parameters: {'max_depth': 9, 'learning_rate': 0.09140037433944197, 'n_estimators': 2177, 'subsample': 0.8958145796806888, 'colsample_bytree': 0.6102004901328572, 'gamma': 3.7350696384928246, 'min_child_weight': 8, 'reg_alpha': 1.6002599086011777, 'reg_lambda': 3.03719869241461}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:16:16,236] Trial 18 finished with value: -0.29740919298698054 and parameters: {'max_depth': 7, 'learning_rate': 0.004793741519956061, 'n_estimators': 3219, 'subsample': 0.7289654160740744, 'colsample_bytree': 0.692713811536603, 'gamma': 2.6364699784077974, 'min_child_weight': 3, 'reg_alpha': 0.5577871819907199, 'reg_lambda': 5.683985993778875}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:16:49,621] Trial 19 finished with value: -0.29288206474707074 and parameters: {'max_depth': 6, 'learning_rate': 0.15897161614218797, 'n_estimators': 2901, 'subsample': 0.6147524356986708, 'colsample_bytree': 0.5017995208838487, 'gamma': 1.9366745029907158, 'min_child_weight': 7, 'reg_alpha': 2.347583379920249, 'reg_lambda': 7.813147946458994}. Best is trial 6 with value: -0.28765412793291967.
[I 2026-07-13 22:17:20,689] Trial 20 finished with value: -0.28173421225363404 and parameters: {'max_depth': 9, 'learning_rate': 0.022824801985675436, 'n_estimators': 1998, 'subsample': 0.503968366675025, 'colsample_bytree': 0.8255789388307577, 'gamma': 0.8920932554257768, 'min_child_weight': 4, 'reg_alpha': 1.2999412563930968, 'reg_lambda': 5.379753365213308}. Best is trial 20 with value: -0.28173421225363404.
[I 2026-07-13 22:17:50,666] Trial 21 finished with value: -0.28099414126509725 and parameters: {'max_depth': 9, 'learning_rate': 0.021984924502054595, 'n_estimators': 1999, 'subsample': 0.5574691782873071, 'colsample_bytree': 0.8361518003064665, 'gamma': 0.8522805990354372, 'min_child_weight': 2, 'reg_alpha': 1.235739708628139, 'reg_lambda': 5.707709659917802}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:18:18,614] Trial 22 finished with value: -0.28202838404017583 and parameters: {'max_depth': 9, 'learning_rate': 0.022769245460136908, 'n_estimators': 1943, 'subsample': 0.5023507984579182, 'colsample_bytree': 0.8629045050438533, 'gamma': 0.7709594317928582, 'min_child_weight': 4, 'reg_alpha': 1.473453801346234, 'reg_lambda': 4.607000146852521}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:18:44,436] Trial 23 finished with value: -0.2827926681784931 and parameters: {'max_depth': 9, 'learning_rate': 0.02090338798030505, 'n_estimators': 1805, 'subsample': 0.5012405713638628, 'colsample_bytree': 0.8696975477399987, 'gamma': 0.8704742340225156, 'min_child_weight': 4, 'reg_alpha': 1.9124515569037763, 'reg_lambda': 4.631477178611068}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:19:02,958] Trial 24 finished with value: -0.2849043470444087 and parameters: {'max_depth': 9, 'learning_rate': 0.02140790213384175, 'n_estimators': 1269, 'subsample': 0.5016255992946776, 'colsample_bytree': 0.8309404646418361, 'gamma': 0.9572330688049308, 'min_child_weight': 2, 'reg_alpha': 2.8388787848837493, 'reg_lambda': 3.496623733939496}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:19:43,609] Trial 25 finished with value: -0.28286183645288754 and parameters: {'max_depth': 10, 'learning_rate': 0.007148763092394048, 'n_estimators': 2203, 'subsample': 0.5582398563778205, 'colsample_bytree': 0.8986095209734897, 'gamma': 1.0882876113257793, 'min_child_weight': 4, 'reg_alpha': 1.3807879021547302, 'reg_lambda': 2.241682587570856}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:20:18,617] Trial 26 finished with value: -0.29508252698798937 and parameters: {'max_depth': 9, 'learning_rate': 0.0036444162196982675, 'n_estimators': 1881, 'subsample': 0.5379386466616045, 'colsample_bytree': 0.9968335756120521, 'gamma': 1.6669158074869501, 'min_child_weight': 2, 'reg_alpha': 2.9954901506002964, 'reg_lambda': 5.202615585364964}. Best is trial 21 with value: -0.28099414126509725.
[I 2026-07-13 22:20:48,521] Trial 27 finished with value: -0.2805326488904811 and parameters: {'max_depth': 10, 'learning_rate': 0.019529091445061715, 'n_estimators': 1459, 'subsample': 0.5883514292955502, 'colsample_bytree': 0.7918787949318857, 'gamma': 0.6933136953636898, 'min_child_weight': 5, 'reg_alpha': 1.2304509261071075, 'reg_lambda': 4.203027467460618}. Best is trial 27 with value: -0.2805326488904811.
[I 2026-07-13 22:21:21,386] Trial 28 finished with value: -0.2846953636531818 and parameters: {'max_depth': 10, 'learning_rate': 0.007607940660355929, 'n_estimators': 1439, 'subsample': 0.5827628547067526, 'colsample_bytree': 0.7882847060369298, 'gamma': 0.07193506527492877, 'min_child_weight': 5, 'reg_alpha': 1.9870644594911167, 'reg_lambda': 4.030549191666871}. Best is trial 27 with value: -0.2805326488904811.
[I 2026-07-13 22:21:40,819] Trial 29 finished with value: -0.3874195100327097 and parameters: {'max_depth': 10, 'learning_rate': 0.0019308873595676188, 'n_estimators': 816, 'subsample': 0.6001378326262554, 'colsample_bytree': 0.7451498233292534, 'gamma': 1.2680311638152126, 'min_child_weight': 3, 'reg_alpha': 1.242547120830384, 'reg_lambda': 2.230930241117627}. Best is trial 27 with value: -0.2805326488904811.
[I 2026-07-13 22:22:26,239] Trial 30 finished with value: -0.28011954512688597 and parameters: {'max_depth': 9, 'learning_rate': 0.07554718318875307, 'n_estimators': 2238, 'subsample': 0.6340966520873422, 'colsample_bytree': 0.928727468853882, 'gamma': 0.5981581237885003, 'min_child_weight': 6, 'reg_alpha': 2.6021091009509543, 'reg_lambda': 7.546180172788924}. Best is trial 30 with value: -0.28011954512688597.
[I 2026-07-13 22:23:12,861] Trial 31 finished with value: -0.2800317823022899 and parameters: {'max_depth': 9, 'learning_rate': 0.06373591610195391, 'n_estimators': 2181, 'subsample': 0.6216897834806957, 'colsample_bytree': 0.934082315181667, 'gamma': 0.4815974374490627, 'min_child_weight': 6, 'reg_alpha': 3.450766266215201, 'reg_lambda': 7.472197693575838}. Best is trial 31 with value: -0.2800317823022899.
[I 2026-07-13 22:24:03,303] Trial 32 finished with value: -0.278830703908779 and parameters: {'max_depth': 10, 'learning_rate': 0.06318870495645393, 'n_estimators': 2322, 'subsample': 0.6413069440852825, 'colsample_bytree': 0.939596404428022, 'gamma': 0.5020046067708431, 'min_child_weight': 6, 'reg_alpha': 3.6522090588757874, 'reg_lambda': 7.7800224934494935}. Best is trial 32 with value: -0.278830703908779.
[I 2026-07-13 22:24:40,699] Trial 33 finished with value: -0.27900997979717734 and parameters: {'max_depth': 10, 'learning_rate': 0.07644054206215138, 'n_estimators': 2311, 'subsample': 0.6269198779680264, 'colsample_bytree': 0.9661278432790764, 'gamma': 0.49357984909359665, 'min_child_weight': 6, 'reg_alpha': 3.750189530586673, 'reg_lambda': 7.780303642592947}. Best is trial 32 with value: -0.278830703908779.
[I 2026-07-13 22:25:18,777] Trial 34 finished with value: -0.27889647350566094 and parameters: {'max_depth': 10, 'learning_rate': 0.06941841437748097, 'n_estimators': 2349, 'subsample': 0.6375018607308468, 'colsample_bytree': 0.930909745392632, 'gamma': 0.3972120552680671, 'min_child_weight': 6, 'reg_alpha': 3.7900530962770085, 'reg_lambda': 7.645717203009113}. Best is trial 32 with value: -0.278830703908779.
[I 2026-07-13 22:25:59,175] Trial 35 finished with value: -0.2781200703535932 and parameters: {'max_depth': 10, 'learning_rate': 0.0656182618076613, 'n_estimators': 2371, 'subsample': 0.6468220449697093, 'colsample_bytree': 0.9496466295381796, 'gamma': 0.3324833654395244, 'min_child_weight': 6, 'reg_alpha': 3.5914209919759403, 'reg_lambda': 8.46664597422983}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:26:46,766] Trial 36 finished with value: -0.2810138473769861 and parameters: {'max_depth': 10, 'learning_rate': 0.12850954515220242, 'n_estimators': 2852, 'subsample': 0.6769264921851516, 'colsample_bytree': 0.9997376313691996, 'gamma': 0.33399241090577825, 'min_child_weight': 8, 'reg_alpha': 4.710356552335697, 'reg_lambda': 8.600727434682023}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:27:13,800] Trial 37 finished with value: -0.28522352496319264 and parameters: {'max_depth': 10, 'learning_rate': 0.2467531593125829, 'n_estimators': 1640, 'subsample': 0.6508338175655375, 'colsample_bytree': 0.9628407538028668, 'gamma': 0.33845545306332075, 'min_child_weight': 7, 'reg_alpha': 3.8774524944456674, 'reg_lambda': 8.550060370709554}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:27:48,034] Trial 38 finished with value: -0.28284770047318053 and parameters: {'max_depth': 10, 'learning_rate': 0.03667504447907082, 'n_estimators': 2280, 'subsample': 0.6473195384459666, 'colsample_bytree': 0.9548056633106063, 'gamma': 1.320177885344843, 'min_child_weight': 6, 'reg_alpha': 3.9971708577811245, 'reg_lambda': 9.211421406856337}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:28:28,244] Trial 39 finished with value: -0.28027631355181293 and parameters: {'max_depth': 10, 'learning_rate': 0.11344165131031415, 'n_estimators': 2395, 'subsample': 0.6520970565408301, 'colsample_bytree': 0.9122449884621734, 'gamma': 0.12363143667514315, 'min_child_weight': 9, 'reg_alpha': 3.4589677716741294, 'reg_lambda': 8.299069094807312}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:29:04,585] Trial 40 finished with value: -0.2849378224145469 and parameters: {'max_depth': 10, 'learning_rate': 0.06944035983164158, 'n_estimators': 2941, 'subsample': 0.6949112808420684, 'colsample_bytree': 0.9789933794582795, 'gamma': 1.7008942323492464, 'min_child_weight': 5, 'reg_alpha': 4.310714629349933, 'reg_lambda': 9.628140664089008}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:29:40,106] Trial 41 finished with value: -0.2800131148234916 and parameters: {'max_depth': 9, 'learning_rate': 0.061985904881812576, 'n_estimators': 2389, 'subsample': 0.6107071726173872, 'colsample_bytree': 0.9335646856859637, 'gamma': 0.5222413772048535, 'min_child_weight': 6, 'reg_alpha': 3.50876997392685, 'reg_lambda': 7.377273087315618}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:30:14,052] Trial 42 finished with value: -0.28175194860881836 and parameters: {'max_depth': 8, 'learning_rate': 0.056337447836322135, 'n_estimators': 2466, 'subsample': 0.5814546972600608, 'colsample_bytree': 0.9375914842475396, 'gamma': 0.45348129708702306, 'min_child_weight': 6, 'reg_alpha': 3.5546927871092584, 'reg_lambda': 7.127864699831623}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:31:17,847] Trial 43 finished with value: -0.2786160628895568 and parameters: {'max_depth': 10, 'learning_rate': 0.08330159684215944, 'n_estimators': 3997, 'subsample': 0.6141308494820015, 'colsample_bytree': 0.8746764305526903, 'gamma': 0.2265948696752938, 'min_child_weight': 7, 'reg_alpha': 3.780226764165098, 'reg_lambda': 6.32175951052305}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:32:13,127] Trial 44 finished with value: -0.278684252237296 and parameters: {'max_depth': 10, 'learning_rate': 0.09339626526698538, 'n_estimators': 3400, 'subsample': 0.6505506141515948, 'colsample_bytree': 0.8685578963776944, 'gamma': 0.2246372627531806, 'min_child_weight': 7, 'reg_alpha': 4.437036650395593, 'reg_lambda': 6.290259682725613}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:33:07,592] Trial 45 finished with value: -0.2807795832573137 and parameters: {'max_depth': 10, 'learning_rate': 0.1489949039937733, 'n_estimators': 3282, 'subsample': 0.6551885151719753, 'colsample_bytree': 0.8691677421107065, 'gamma': 0.18513840168024887, 'min_child_weight': 7, 'reg_alpha': 4.345745031703912, 'reg_lambda': 6.365646526522075}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:34:03,953] Trial 46 finished with value: -0.28411304573534013 and parameters: {'max_depth': 10, 'learning_rate': 0.21584069260392613, 'n_estimators': 3831, 'subsample': 0.740624235074691, 'colsample_bytree': 0.9003123185368551, 'gamma': 1.1258972240640794, 'min_child_weight': 8, 'reg_alpha': 4.74961524284663, 'reg_lambda': 6.459465421326577}. Best is trial 35 with value: -0.2781200703535932.
[I 2026-07-13 22:34:59,462] Trial 47 finished with value: -0.2780343838775909 and parameters: {'max_depth': 9, 'learning_rate': 0.0985439723491344, 'n_estimators': 3478, 'subsample': 0.9899684193033329, 'colsample_bytree': 0.8497880481904895, 'gamma': 0.2376502582358856, 'min_child_weight': 7, 'reg_alpha': 3.212309415904343, 'reg_lambda': 8.903910137181736}. Best is trial 47 with value: -0.2780343838775909.

Best Score : -0.27511947927427527
Best Params: {'max_depth': 10, 'learning_rate': 0.05953139963770414, 'n_estimators': 2747, 'subsample': 0.8337433250519926, 'colsample_bytree': 0.7543943678414979, 'gamma': 0.032771478039126015, 'min_child_weight': 6, 'reg_alpha': 1.716855990003528, 'reg_lambda': 6.819289477686187}

best param = {'max_depth': 10, 'learning_rate': 0.05953139963770414, 'n_estimators': 2747, 'subsample': 0.8337433250519926, 'colsample_bytree': 0.7543943678414979, 'gamma': 0.032771478039126015, 'min_child_weight': 6, 'reg_alpha': 1.716855990003528, 'reg_lambda': 6.819289477686187}

In [60]:
train_single_model(
    model_name = "XGBoost",
    model = models_dict["XGBoost"],
    X_train = X_train,
    y_train = y_train,
    X_test = X_test,
    y_test = y_test
)

                 feature  importance
4           land_size_m2    0.105037
14    city_Jakarta Timur    0.083150
5       building_size_m2    0.075462
15    city_Jakarta Utara    0.064763
16          sub_district    0.061171
11    city_Jakarta Barat    0.058092
13  city_Jakarta Selatan    0.058018
12    city_Jakarta Pusat    0.054475
0               district    0.053248
9                    tol    0.051217

{'Model': 'XGBoost',
 'R2 Score': 0.9256936062627593,
 'MAE (mean)': 1959068073.4933982,
 'MDAE (median)': 654203647.9999933,
 'MAPE': 0.182980686090712,
 'Q25': np.float64(0.04635522535816529),
 'Q50': np.float64(0.12054813257142666),
 'Q75': np.float64(0.2373373264030097)}